[package]
name = "debug_events"
version = "0.1.0"
edition = "2021"


[dependencies]
zwuevi = { version = "0.1", path = "../../" }
tokio = { version = "^1", features = ["rt-multi-thread", "io-util", "macros", "sync", "time", "net"] }
